In [36]:
import numpy as np
import pandas as pd

In [37]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [38]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [39]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [40]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [41]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
model.get_weights()

[array([[-0.8812394 ,  1.0154966 ],
        [ 0.38069403, -1.1439524 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.8752409],
        [-1.1395587]], dtype=float32),
 array([0.], dtype=float32)]

In [43]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
            np.array([0., 0.], dtype=np.float32),
            np.array([[0.1], [0.1]], dtype=np.float32),
            np.array([0.], dtype=np.float32)]

In [44]:
model.set_weights(new_weights)

In [45]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [46]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [47]:
model.fit(df.iloc[:,:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)


Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 23.5692
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.6413 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.1160 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 28.5433 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.4988 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.0168 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.0820 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.7308 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.9403 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 29.6082 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 27.8670 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.8400 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.7234 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.5069 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.0832 
Epoch 16/75
4/4 ━━━━

In [48]:
model.get_weights()

[array([[0.37359524, 0.37359524],
        [0.36586398, 0.36586398]], dtype=float32),
 array([0.27243444, 0.27243444], dtype=float32),
 array([[0.37305844],
        [0.37305844]], dtype=float32),
 array([0.20498286], dtype=float32)]