In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [16]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [17]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [18]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.get_weights()

[array([[-0.22731388,  0.7423769 ],
        [ 0.28599572,  1.2190434 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.32703185],
        [0.881739  ]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
            np.array([0., 0.], dtype=np.float32),
            np.array([[0.1], [0.1]], dtype=np.float32),
            np.array([0.], dtype=np.float32)]

In [22]:
model.set_weights(new_weights)

In [23]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [27]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [28]:
model.fit(df.iloc[:,:-1].values, df['placed'].values, epochs=75, verbose=1, batch_size=1)


Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.6719  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6826 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6826 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6732 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6732 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6559 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7139 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7168 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6565 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7166 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6575 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6567 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7295 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7021 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7060 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━

In [29]:
model.get_weights()

[array([[0.10273103, 0.10273103],
        [0.0810622 , 0.0810622 ]], dtype=float32),
 array([-0.04415063, -0.04415063], dtype=float32),
 array([[0.08963956],
        [0.08963956]], dtype=float32),
 array([-0.01996237], dtype=float32)]